name: Package Resize

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  
  test:
    name: Test
    uses: ./.github/workflows/wc-test.yml

  package:
    name: Resize
    needs: test
    uses: ./.github/workflows/wc-package.yml
    with:
      lambda_name: 'resize'
      dockerfile_path: 'athena_lambda/serverless/resize'

  
    



  