name: Package Logger

on:
  workflow_dispatch:

jobs:
  
  test:
    name: Test
    #uses: ./.github/workflows/wc-test.yml
    runs-on: ubuntu-latest
    steps:
      - run: echo Test

  package:
    name: Logger
    needs: test
    uses: ./.github/workflows/wc-package.yml
    with:
      lambda_name: 'logger'
      dockerfile_path: 'athena_lambda/serverless/logger'
  